// @vitest-environment jsdom
// Observation suite: successful execution is not financial certification.
import {it,expect} from 'vitest';
import {act,cleanup,renderHook} from '@testing-library/react';
import {createRequire} from 'node:module';
import fs from 'node:fs';
import type {ReactNode} from 'react';
import {AppProvider,useApp} from '../src/store/AppContext';
import {lsClearAll,lsGet,lsSetBatchAwait} from '../src/lib/storage';
import {cashBalanceByMethod} from '../src/lib/cashBalance';
import {formatCurrency} from '../src/lib/format';
import {computeShiftSummary} from '../src/store/_pure';
type R={n:bigint;d:bigint};
const O=createRequire(import.meta.url)('./fin-01-oracle.cjs') as {rational:(v:number|string)=>R;add:(a:R,b:R)=>R;sub:(a:R,b:R)=>R;mul:(a:R,b:R)=>R;invoice:(lines:{price:number;quantity:number}[],discount?:number,shipping?:number)=>R;rng:(seed:number)=>()=>number};
function normalized(r:R){let a=r.n<0n?-r.n:r.n,b=r.d;while(b){const t=b;b=a%b;a=t;}return {n:r.n/(a||1n),d:r.d/(a||1n)};}
const exact=(r:R)=>{const v=normalized(r);return `${v.n}/${v.d}`;};
const number=(r:R)=>{const v=normalized(r);return Number(v.n)/Number(v.d);};
const equal=(actual:number,r:R)=>{if(!Number.isFinite(actual))return false;const a=O.rational(actual);return a.n*r.d===r.n*a.d;};
const evidence:Record<string,unknown>[]=[],failedSeeds=new Set<number>();
const wrapper=({children}:{children:ReactNode})=><AppProvider>{children}</AppProvider>;
function fresh(){cleanup();localStorage.clear();lsClearAll();const h=renderHook(useApp,{wrapper});let product!:ReturnType<typeof useApp>['products'][number],customer!:ReturnType<typeof useApp>['customers'][number],supplier!:ReturnType<typeof useApp>['suppliers'][number];act(()=>{product=h.result.current.addProduct({code:'FIN03',name:'FIN03',category:'FIN03',unit:'unit',purchasePrice:0.1,wholesalePrice:0.333,retailPrice:0.333,quantity:1000,looseQuantity:0,minStock:0,hasExpiry:false,archived:false});customer=h.result.current.addCustomer({name:'FIN03'});supplier=h.result.current.addSupplier({name:'FIN03'});});return {h,product,customer,supplier,opening:h.result.current.currentCashBalance()};}
type F=ReturnType<typeof fresh>;
function line(f:F,q:number,p:number,id='line'){return {id,productId:f.product.id,productName:f.product.name,unit:'unit',quantity:q,price:p,subtotal:q*p};}
async function sale(f:F,q:number,p:number,paid=0,discount=0,shippingFee=0){let invoice!:ReturnType<typeof useApp>['salesInvoices'][number];await act(async()=>{invoice=await f.h.result.current.addSalesInvoice({invoiceNumber:'FIN03-S',date:'2026-10-03',customerId:f.customer.id,customerName:f.customer.name,lines:[line(f,q,p)],total:q*p-discount+shippingFee,discount,shippingFee,amountReceived:paid,paymentType:'account',priceType:'retail'});});return invoice;}
function compare(id:string,actual:number,expected:R,extra:Record<string,unknown>={}){const match=equal(actual,expected);evidence.push({id,actual,expected:exact(expected),exactMatch:match,...extra});if(!match&&typeof extra.seed==='number')failedSeeds.add(extra.seed);}
function snapshot(f:F){const a=f.h.result.current;return JSON.stringify({products:a.products,purchases:a.purchaseInvoices,sales:a.salesInvoices,cash:a.cashEntries,returns:a.salesReturns,purchaseReturns:a.purchaseReturns,movements:a.stockMovements});}
it('records exact FIN-03 decimals, accumulation, payments and 100 reproducible chains',async()=>{
 try{
  for(const [p,count] of [[0.01,100],[0.01,1000],[0.001,1000],[0.333,300],[0.005,1000]] as const){const f=fresh();act(()=>{for(let i=0;i<count;i++)f.h.result.current.addCashEntry({type:'adjustment',amount:p,date:'2026-10-03',description:'FIN03 accumulation'});});await lsSetBatchAwait({cashEntries:f.h.result.current.cashEntries});const expected=O.mul(O.rational(p),O.rational(count));compare('cash-accumulation-'+p+'-'+count,f.h.result.current.currentCashBalance()-f.opening,expected,{count,amount:p,canonicalAmounts:lsGet('cashEntries',[]),methodReport:cashBalanceByMethod(f.h.result.current.cashEntries,0),formatted:formatCurrency(f.h.result.current.currentCashBalance()-f.opening)});}
  for(const paid of [99.99,99.999,100,100.001]){const f=fresh(),inv=await sale(f,1,100,paid);const stored=f.h.result.current.salesInvoices.find(x=>x.id===inv.id)!;evidence.push({id:'sale-threshold-'+paid,invoice:stored,display:{total:formatCurrency(stored.total),paid:formatCurrency(stored.amountReceived),remaining:formatCurrency(stored.remaining)}});}
  for(const p of [0.01,0.1,0.2,0.3,0.333,0.3333,1.001,10.005,99.999,999.999,90071992547409.9,1e12,1e15,1e18,1e100]){const f=fresh(),inv=await sale(f,0.333,p,p*0.333/2);compare('sale-product-'+p,inv.total,O.invoice([{price:p,quantity:0.333}]),{invoice:inv,stored:lsGet('salesInvoices',[]),formatted:formatCurrency(inv.total)});}
  {const f=fresh(),inv=await sale(f,1,1,0);for(let i=0;i<100;i++)act(()=>f.h.result.current.recordSalesReceipt(inv.id,0.005));const a=f.h.result.current.salesInvoices.find(x=>x.id===inv.id)!;compare('repeated-tiny-payment-paid',a.amountReceived,O.rational(0.5),{invoice:a});compare('repeated-tiny-payment-due',a.remaining,O.rational(0.5));}
  for(const payment of [100,99.99,100.01,0.000001,0.333,1e100,NaN,Infinity,-Infinity,-1]){const f=fresh(),inv=await sale(f,1,100,0),before=snapshot(f);let error;try{act(()=>f.h.result.current.recordSalesReceipt(inv.id,payment));}catch(e){error=String(e);}evidence.push({id:'payment-'+String(payment),input:String(payment),error,unchanged:snapshot(f)===before,invoice:f.h.result.current.salesInvoices.find(x=>x.id===inv.id),cash:f.h.result.current.currentCashBalance()-f.opening});}
  {const f=fresh();act(()=>f.h.result.current.addCashEntry({type:'adjustment',amount:1e308,date:'2026-10-03',description:'FIN03 finite cash A'}));act(()=>f.h.result.current.addCashEntry({type:'adjustment',amount:1e308,date:'2026-10-03',description:'FIN03 finite cash B'}));await lsSetBatchAwait({cashEntries:f.h.result.current.cashEntries});evidence.push({id:'finite-cash-derived-overflow',canonicalEntries:lsGet('cashEntries',[]),currentCash:String(f.h.result.current.currentCashBalance()),formatted:formatCurrency(f.h.result.current.currentCashBalance()),finite:Number.isFinite(f.h.result.current.currentCashBalance())});}
  {const shift:ReturnType<typeof useApp>['shifts'][number]={id:'fin-shift',shiftNumber:1,cashierId:'fin-cashier',cashierName:'FIN03',cashierUsername:'fin03',openedAt:'2026-10-03T00:00:00Z',status:'open',openingCash:0,expectedCash:0,totalSalesCount:0,totalSalesAmount:0,totalCashSales:0,totalVisaSales:0,totalCreditSales:0,totalRefunds:0,totalExpenses:0,salesInvoiceIds:[]};const entries=Array.from({length:100},(_,i)=>({id:'cash-'+i,type:'sales-receipt' as const,amount:0.005,date:'2026-10-03',description:'FIN03',paymentMethod:'bank' as const,shiftId:'fin-shift'}));const actual=computeShiftSummary({shift,salesInvoices:[],cashEntries:entries,salesReturns:[]});evidence.push({id:'shift-method-rounding',expectedExact:'1/2',actual});}
  for(let seed=1;seed<=100;seed++){const f=fresh(),random=O.rng(seed),p=(1+Math.floor(random()*999))/1000,q=2+Math.floor(random()*5),buyPrice=(1+Math.floor(random()*999))/1000;let stock=O.rational(1000),cash=O.rational(0),purchase!:ReturnType<typeof useApp>['purchaseInvoices'][number];const buy=O.mul(O.rational(5),O.rational(buyPrice));act(()=>{purchase=f.h.result.current.addPurchaseInvoice({invoiceNumber:'FIN03-P',date:'2026-10-03',supplierId:f.supplier.id,supplierName:f.supplier.name,lines:[line(f,5,buyPrice)],total:buyPrice*5,amountPaid:0});});stock=O.add(stock,O.rational(5));const check=(op:string,customer:R,supplier:R)=>{const a=f.h.result.current;compare(`seed-${seed}-${op}-stock`,a.products.find(x=>x.id===f.product.id)!.quantity,stock,{seed,op});compare(`seed-${seed}-${op}-cash`,a.currentCashBalance()-f.opening,cash,{seed,op});compare(`seed-${seed}-${op}-customer`,a.customerBalance(f.customer.id),customer,{seed,op});compare(`seed-${seed}-${op}-supplier`,a.supplierBalance(f.supplier.id),supplier,{seed,op});};check('purchase',O.rational(0),buy);
   const pp=buyPrice;act(()=>f.h.result.current.recordPurchasePayment(purchase.id,pp));cash=O.sub(cash,O.rational(pp));const supplierDue=O.sub(buy,O.rational(pp));check('supplier-payment',O.rational(0),supplierDue);
   const net=O.invoice([{price:p,quantity:q}],0.001,0.003),inv=await sale(f,q,p,0,0.001,0.003);stock=O.sub(stock,O.rational(q));check('sale',net,supplierDue);
   act(()=>f.h.result.current.addSalesReturn({date:'2026-10-03',originalInvoiceId:inv.id,originalInvoiceNumber:inv.invoiceNumber,customerId:f.customer.id,customerName:f.customer.name,lines:[{...line(f,1,p,'return'),sourceLineId:'line'}],total:p,refundCash:false}));stock=O.add(stock,O.rational(1));const due=O.sub(net,O.rational(p));check('return',due,supplierDue);
   const payment=p/2;act(()=>f.h.result.current.recordSalesReceipt(inv.id,payment));cash=O.add(cash,O.rational(payment));const customerDue=O.sub(due,O.rational(payment));check('customer-payment',customerDue,supplierDue);
   const adjustment=(1+Math.floor(random()*33))/1000;act(()=>f.h.result.current.addCashEntry({type:'adjustment',amount:-adjustment,date:'2026-10-03',description:'FIN03'}));cash=O.sub(cash,O.rational(adjustment));check('cash',customerDue,supplierDue);evidence.push({id:'seed-'+seed,seed,inputs:{p,q,buyPrice,pp,payment,adjustment},canonical:JSON.parse(snapshot(f)),methodReport:cashBalanceByMethod(f.h.result.current.cashEntries,0),expected:{cash:exact(cash),stock:exact(stock),customer:exact(customerDue),supplier:exact(supplierDue)},expectedNumbers:{cash:number(cash)}});
  }
 }finally{cleanup();fs.writeFileSync('reports/financial-accounting-audit-2026-10/fin-03-store-evidence.json',JSON.stringify({layer:'actual AppProvider/localStorage; not Electron/SQLite',evidence,failedSeeds:[...failedSeeds]},(_k,v)=>typeof v==='number'&&!Number.isFinite(v)?String(v):v,2));}
 expect(evidence.filter(x=>String(x.id).match(/^seed-\d+$/))).toHaveLength(100);
});
